### ISSUE TITLE
consider selling it

### ISSUE THREAD

**Issue by burakfirik** [Brian-Gaffney/Deb.ug#1]
Hi Brian,
I have a interest for your deb.ug site to deploy a project, would you consider selling it ? I would really appreciate your response 

thank you very much
-Burak

**Comment by Brian-Gaffney** [comment]
Hi Burak.

I'm not interested in selling this domain.

Best of luck finding another domain for your project!

Cheers.

**Comment by burakfirik** [comment]
Thank you Brian, I really appreciate your quick response, 
would not you consider $3k for the domain only?

**Comment by Brian-Gaffney** [comment]
Sorry Burak but I'm really not interested in selling it.

**Comment by burakfirik** [comment]
Hi Brian,
My partner Ahmad contacted you as well, we will make final offer of $8900 because that is our budget from MIT for the project. Please help us.

Let me know. I look forward to your response.

Thanks.

**Comment by Brian-Gaffney** [comment]
Sorry guys I'm really not interested in selling.

It's a very generous offer but this is my personal domain that I plan to
use forever.
It has sentimental value to me.

I do wish you the best of luck finding one for your project!

Out of pure curiosity, what is the project?

**Comment by burakfirik** [comment]
Hi Brian:

Argh, that sucks for us. We really were hoping that you'd help us out here, but I guess I understand we'd have to continue our conquest.

We wanted to create an educational site, to help minority students(think Aborigines of your country)learn Computer Science skills, so they can apply them for meaningful projects. We figured what's a better domain than debug(deb.ug)?right.

I am a student at MIT, and was collaborating with a couple of my friends to work on this. Please let me know if you can help out, I'd even buy you another a domain name of your choice, for 5 years, plus the payment promised, simply because I really like the domain name.

Thanks.
-BF
